### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by mlaclair2009**
Completed Log creation, updating of logs.txt, and implemented password protection on main login screen.

### CODE REVIEW

**Comment by stephenglunt** [comment]
I tried merging via command line.  This was the message I got:

$ git merge origin/21-APR-Matt
Auto-merging LOG.java
CONFLICT (content): Merge conflict in LOG.java
Auto-merging EntryList.java
CONFLICT (content): Merge conflict in EntryList.java
Automatic merge failed; fix conflicts and then commit the result.

I'm not sure what the conflict is with LOG.java and EntryList.java.  Do you know how to merge these?

**Comment by mlaclair2009** [comment]
Possibly because I renamed panel to paneltop? I added an additional panel
to the bottom of the screen for the save button.

**Comment by stephenglunt** [comment]
Do you have any ideas for how to merge?  I know we had a problem like this before.  I don't know who was able to get it to work.  I know it wasn't me.

**Comment by zMerlin** [comment]
Why the rename? 

```
On Thursday, April 21, 2016 11:03 AM, Matt <notifications@github.com> wrote:
```

 Possibly because I renamed panel to paneltop? I added an additional panel
to the bottom of the screen for the save button.

**Comment by mlaclair2009** [comment]
I can get rid of the rename. Changed it to paneltop and added panelbottom
or I can just upload all the files and overwrite what's on there. Shouldn't
be an issue since nobody else has made additional changes

**Comment by stephenglunt** [comment]
This was closed but has unmerged commits.

**Pull request closed without merging**
